### ISSUE TITLE
Feat : AzureSDK를 이용하여 클라우드 모델 구축 

### ISSUE THREAD

**Issue by hyunw9** [Team-Clody/Clody_server#137]
## 📌  Feature Issue

Azure openai SDK를 이용하여 클라우드 상 GPT 모델을 구현합니다. 

## 📝  To-do
- [x] 요청 전송 로직 구현 
- [x] 응답 시 삭제 여부 확인하여 DB 반영

**Comment by Yangdaehan** [comment]
azure 가보자고
